name: ci

on:
  - push

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm clean-install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --reporter=verbose

  integration-test:
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm clean-install

      - name: Build docker image
        run: docker build .  -t receipt-processor:1

      - name: Start docker container
        run: docker run -d --name receipt-processor -p 3000:3000 receipt-processor:1

      - name: Run integration tests
        run: npm run test:integration -- --reporter=verbose

      - name: Stop docker container
        if: always()
        run: docker stop receipt-processor
